# core service setup
core.id=ckpouch-data-interface
core.name=CKPouch Data Interface Server
core.version=v1.0.0
core.svcdir=/home/ubuntu/ckpush4/ckpush4-server/ckpouch-data-interface/service
core.event-map=/conf/event-map.cfg.json
core.scheduler-map=/conf/load-schedule.cfg.json
core.http-map=/conf/http-map.cfg.json
#core.mqtt-map=/conf/mqtt-map.cfg.json
# core.redis-map=/conf/redis-map.cfg.json
core.module-map=/conf/load-modules.cfg.json

# log
log.console=true
log.out=/data/log/ckpouch/ckpouch-data-interface-out.log
log.err=/data/log/ckpouch/ckpouch-data-interface-err.log
log.max-files=14d
log.default-level=debug
log.scheduler-level=debug

# http setup
# usage : http.{alias}.{config}
http.core.port=12003
http.core.protocol=http

# ws setup
# usage : ws.{alias}.{config}

# mysql setup
# usage : mysql.{alias}.{config}
#mysql.core.host=localhost
mysql.core.host=
mysql.core.port=3306
mysql.core.username=ckpush4_user
mysql.core.password=
mysql.core.max-conn-count=10
mysql.core.db=ck_cms_db

# redis setup
# usage : redis.{alias}.{config}
redis.device-ping.host=
redis.device-ping.port=
redis.device-ping.password=
redis.device-ping.db=
redis.device-ping.psubscribe=[]
redis.device-ping.subscribe=[]

# mqtt setup
# usage : mqtt.{alias}.{config}

# rabbitmq setup
# usage : rabbitmq.{alias}.{config}

# service setup
# usage : service.{config}
service.push.protocol=http
service.push.host=localhost
service.push.port=12010
service.push.path=/push/msg/send
