# core service setup
core.id=ckpouch-data-interface
core.name=CKPouch Data Interface Server
core.version=v1.0.0
core.svcdir=/home/ckstack/rk-data-stat/ckpouch-data-interface/service
core.event-map=/conf/event-map.cfg.json
core.scheduler-map=/conf/load-schedule.cfg.json
core.http-map=/conf/http-map.cfg.json
#core.mqtt-map=/conf/mqtt-map.cfg.json
# core.redis-map=/conf/redis-map.cfg.json
core.module-map=/conf/load-modules.cfg.json

# log
log.console=true
log.out=/data/log/ckpouch/ckpouch-data-interface-out.log
log.err=/data/log/ckpouch/ckpouch-data-interface-err.log
log.max-files=14d
log.default-level=debug

# http setup
# usage : http.{alias}.{config}
http.core.port=12003
http.core.protocol=http

# ws setup
# usage : ws.{alias}.{config}

# postgresql setup
postgresql.history.host=192.168.0.253
postgresql.history.port=5432
postgresql.history.username=ckstack
postgresql.history.password=abcd1234
postgresql.history.max-conn-count=3
postgresql.history.db=ck_history_db
postgresql.history.show-query=true

postgresql.stat.host=192.168.0.253
postgresql.stat.port=5432
postgresql.stat.username=ckstack
postgresql.stat.password=abcd1234
postgresql.stat.max-conn-count=3
postgresql.stat.db=ck_stat_db
postgresql.stat.show-query=true

# redis setup
# usage : redis.{alias}.{config}
redis.device-ping.host=192.168.0.191
redis.device-ping.port=6378
redis.device-ping.password=
redis.device-ping.db=8
redis.device-ping.psubscribe=[]
redis.device-ping.subscribe=[]

# mqtt setup
# usage : mqtt.{alias}.{config}

# rabbitmq setup
# usage : rabbitmq.{alias}.{config}

# service setup
# usage : service.{config}
service.device-list.save-path-csv=/data/files/device-list/YYYY/MM/DD/device-list-YYYYMMDDHHmmss.csv
service.device-list.save-path=/data/files/device-list/YYYY/MM/DD/device-list-YYYYMMDDHHmmss.json
service.device-list.retention-days=30

service.weather.save-path=/data/files/weather/YYYY/MM/DD/weather-YYYYMMDDHHmmss.csv
service.weather.retention-days=30
