/**
 * tbl_stat_src
 * stat source raw table (backup/sync capable)
 */
-- stat src
-- DROP TABLE public.tbl_stat_src;
-- TODO partition
-- create table
CREATE TABLE public.tbl_stat_src (
  stat_date  CHAR(14) NOT NULL,
  serial_num CHAR(17) NOT NULL,
  data_type  CHAR(32) NOT NULL,
  value      INTEGER,
  fvalue     INTEGER
);

-- add comment for column
COMMENT ON TABLE public.tbl_stat_src IS 'stat source raw table';
COMMENT ON COLUMN public.tbl_stat_src.stat_date IS 'statistic date. YYYYMMDDHHmmss';
COMMENT ON COLUMN public.tbl_stat_src.serial_num IS 'boiler serial number';
COMMENT ON COLUMN public.tbl_stat_src.data_type IS 'statistic type';
COMMENT ON COLUMN public.tbl_stat_src.value IS 'statistic value or integer part of statistic value';
COMMENT ON COLUMN public.tbl_stat_src.value IS 'fractional part of statistic value';

-- TODO index query 별도 분리
-- ad index
-- 전체 장비도 조회할 수 있으니 일단 순서를 data_type 에 serial_num 으로 변경
CREATE INDEX idx_serial_num_stat_date_data_type ON public.tbl_stat_src (serial_num, stat_date, data_type);

-- add comment for index
COMMENT ON INDEX public.idx_serial_num_stat_date_data_type IS 'index for statistic query by serial_num, stat_date, data_type';


/**
 * tbl_energy_goal
 * stat source raw table (backup/sync capable)
 */
-- stat src
-- DROP TABLE public.tbl_stat_src;
-- TODO partition
-- create table
CREATE TABLE public.tbl_energy_goal (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  serial_num CHAR(17) NOT NULL,
  goal       INTEGER NOT NULL,
  c_date     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  u_date     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- add comment for column
COMMENT ON TABLE public.tbl_energy_goal IS 'stat source raw table';
COMMENT ON COLUMN public.tbl_energy_goal.id IS 'id';
COMMENT ON COLUMN public.tbl_energy_goal.serial_num IS 'boiler serial number';
COMMENT ON COLUMN public.tbl_energy_goal.goal IS 'energy goal value';
COMMENT ON COLUMN public.tbl_energy_goal.c_date IS 'create time';
COMMENT ON COLUMN public.tbl_energy_goal.u_date IS 'update time';

-- TODO index query 별도 분리
-- ad index
-- 전체 장비도 조회할 수 있으니 일단 순서를 data_type 에 serial_num 으로 변경
-- CREATE INDEX idx_serial_num_stat_date_data_type3 ON public.tbl_stat_src3 (serial_num, stat_date, data_type);

-- add comment for index
-- COMMENT ON INDEX public.idx_serial_num_stat_date_data_type3 IS 'index for statistic query by serial_num, stat_date, data_type';
