log: 
  default-level: debug

databases:
  stat:
    engine: postgresql
    host: 192.168.0.253
    port: 5432
    dbname: ck_stat_db
    user: ckstack
    password: env://DB_PASSWORD_CK_STAT_DB
    pool:
      min: 1
      max: 5

  history:
    engine: postgresql
    host: 192.168.0.253
    port: 5432
    dbname: ck_history_db
    user: ckstack
    password: env://DB_PASSWORD_CK_HISTORY_DB
    pool:
      min: 1
      max: 10

data-interface:
  host: http://192.168.0.253:12003
  api:
    device-list:
      method: POST
      path: /api/device/list
