# core service setup
core.id=ckpouch-data-producer
core.name=CKPouch Data Producer Server
core.version=v1.0.0
core.svcdir=/home/ckstack/rk-data-stat/ckpouch-data-producer/service
core.event-map=/conf/event-map.cfg.json
core.scheduler-map=/conf/load-schedule.cfg.json
core.http-map=/conf/http-map.cfg.json
#core.mqtt-map=/conf/mqtt-map.cfg.json
# core.redis-map=/conf/redis-map.cfg.json
core.module-map=/conf/load-modules.cfg.json

# log
log.console=true
log.out=/data/log/ckpouch/ckpouch-data-producer-out.log
log.err=/data/log/ckpouch/ckpouch-data-producer-err.log
log.max-files=14d
log.default-level=debug

# http setup
# usage : http.{alias}.{config}
http.core.port=12010
http.core.protocol=http

# ws setup
# usage : ws.{alias}.{config}

# mysql setup
# usage : mysql.{alias}.{config}
#mysql.core.host=localhost
mysql.core.host=192.168.0.251
mysql.core.port=3306
mysql.core.username=ckpush4_user
mysql.core.password=PpZeegrFJTefMreQyXY7tjUL
mysql.core.max-conn-count=10
mysql.core.db=ckpush4_core_db

# service setup
# usage : service.{config}
service.stat.interface.protocol=http
service.stat.interface.host=localhost
service.stat.interface.port=12003