# core service setup
core.id=ckpouch-data-interface
core.name=CKPouch Data Interface Server
core.version=v1.0.0
core.svcdir=/home/ckstack/rk-data-stat/ckpouch-data-interface/service
core.event-map=/conf/event-map.cfg.json
core.scheduler-map=/conf/load-schedule.cfg.json
core.http-map=/conf/http-map.cfg.json
#core.mqtt-map=/conf/mqtt-map.cfg.json
# core.redis-map=/conf/redis-map.cfg.json
core.module-map=/conf/load-modules.cfg.json

# log
log.console=true
log.out=/data/log/ckpouch/ckpouch-data-interface-out.log
log.err=/data/log/ckpouch/ckpouch-data-interface-err.log
log.max-files=14d
log.default-level=debug

# http setup
# usage : http.{alias}.{config}
http.core.port=12003
http.core.protocol=http

# ws setup
# usage : ws.{alias}.{config}

# psql setup
psql.history.host=192.168.0.254
psql.history.port=5432
psql.history.username=ckstack
psql.history.password=abcd1234
psql.history.max-conn-count=3
psql.history.db=ck_history_db
psq.history.show-query=true

# redis setup
# usage : redis.{alias}.{config}
redis.device-ping.host=192.168.0.191
redis.device-ping.port=6378
redis.device-ping.password=
redis.device-ping.db=8
redis.device-ping.psubscribe=[]
redis.device-ping.subscribe=[]

# mqtt setup
# usage : mqtt.{alias}.{config}

# rabbitmq setup
# usage : rabbitmq.{alias}.{config}

# service setup
# usage : service.{config}
service.push.protocol=http
service.push.host=localhost
service.push.port=12010
service.push.path=/push/msg/send
service.ckpush4.aes.secret=278b9360508211e9b5304190c0bf35b2
service.ckpush4.aes.iv=78b2e9b808b62d05