log: 
  default-level: debug

mqtt:
  host: localhost
  port: 1883

databases:
  stat:
    engine: postgresql
    host: localhost
    port: 5432
    dbname: ck_stat_db
    user: ckstack
    password: env://DB_PASSWORD_CK_STAT_DB
    pool:
      min: 1
      max: 5

  history:
    engine: postgresql
    host: localhost
    port: 5432
    dbname: ck_history_db
    user: ckstack
    password: env://DB_PASSWORD_CK_HISTORY_DB
    pool:
      min: 1
      max: 10
